spring:
  application:
    name: trainee
  liquibase:
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      port: ${REDIS_PORT}
  cache:
    type: redis